language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-19mode
env:
  global:
    - SHOW_SIDEKIQ=true
  matrix:
    - SIDEKIQ_VERSION="~>2.4.0"
    - SIDEKIQ_VERSION="~>2.6.5"
    - SIDEKIQ_VERSION="~>2.8.0"
    - SIDEKIQ_VERSION="~>2.10.0"
    - SIDEKIQ_VERSION="~>2.12.0"
    - SIDEKIQ_VERSION="~>2.13.0"
    - SIDEKIQ_VERSION="~>2.14.0"
    - SIDEKIQ_VERSION="~>2.15.0"
    - SIDEKIQ_VERSION="~>2.16.0"
    - SIDEKIQ_VERSION="~>2.17.0"
script: bundle exec rake
services:
  - redis-server
